name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cargo install dioxus-cli
        rustup target add wasm32-unknown-unknown
    - name: Build
      run: dx build --features web --release
    - name: Run tests
      run: cargo test --verbose
